const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const CLEAR_CART = 'CLEAR_CART';
const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
const SYNCHRONIZE_WITH_LOCAL_STORAGE = 'SYNCHRONIZE_WITH_LOCAL_STORAGE';

export default {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    CLEAR_CART,
    INCREASE_QUANTITY,
    DECREASE_QUANTITY,
    SYNCHRONIZE_WITH_LOCAL_STORAGE
}
