const SET_EMAIL = 'SET_EMAIL';
const SET_PASSWORD = 'SET_PASSWORD';
const SET_FULL_NAME = 'SET_FULL_NAME';
const SET_CONFIRM_PASSWORD = 'SET_CONFIRM_PASSWORD';

export default {
    SET_EMAIL,
    SET_PASSWORD,
    SET_FULL_NAME,
    SET_CONFIRM_PASSWORD,
}