const CREATE_ORDER = 'CREATE_ORDER';
const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
const CANCEL_ORDER = 'CANCEL_ORDER';
const START_DELIVERY_TIMER = 'START_DELIVERY_TIMER';

export default {
    CREATE_ORDER,
    UPDATE_ORDER_STATUS,
    CANCEL_ORDER,
    START_DELIVERY_TIMER
}