export {Home} from './Home';
export {About} from './About';
export {Catalog} from './Catalog';
export {CatalogItemDetails} from './CatalogItemDetails';
export {Reviews} from './Reviews';
export {FAQ} from './FAQ';
export {Delivery} from './Delivery';
export {UserProfileDetails} from './UserProfileDetails';
export {Profile} from './Profile'
export {AuthModal} from './AuthModal'
export {Error} from './Error'